apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# 1. 远程资源引用：锁定版本号是 SRE 的核心准则
resources:
  - https://github.com/fluxcd/flux2/manifests/install?ref=v2.7.5

# 2. 命名空间强制指定
namespace: flux-system