apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: auth-rustfs
  namespace: flux-system
spec:
  interval: 1m
  targetNamespace: rustfs
  sourceRef:
    kind: GitRepository
    name: k3s-private-repo  # 引用你已经建好的源
  path: "./common/auth/rustfs" # 指向仓库里的具体目录
  prune: true
  wait: true